#!/bin/sh

MAC=$(cat /sys/class/net/eth0/address | sed 's/://g')

echo "Updating ddns entries for $MAC"

echo "Update dns.eecs"
/home/debian/gateway/software/ddns/ddns.py --zone device.lab11.eecs.umich.edu --nameserver dns.eecs.umich.edu $MAC.device.lab11.eecs.umich.edu -k /etc/swarm-gateway/ddns/Kswarmgateway.device.lab11.eecs.umich.edu.+165+08430.key -v

echo "Update eecsdns.eecs"
/home/debian/gateway/software/ddns/ddns.py --zone device.lab11.eecs.umich.edu --nameserver eecsdns.eecs.umich.edu $MAC.device.lab11.eecs.umich.edu -k /etc/swarm-gateway/ddns/Kswarmgateway.device.lab11.eecs.umich.edu.+165+08430.key -v

echo "Update csedns.eecs"
/home/debian/gateway/software/ddns/ddns.py --zone device.lab11.eecs.umich.edu --nameserver csedns.eecs.umich.edu $MAC.device.lab11.eecs.umich.edu -k /etc/swarm-gateway/ddns/Kswarmgateway.device.lab11.eecs.umich.edu.+165+08430.key -v

echo "Done."

